### ISSUE TITLE
Display `count-api` data in "settings"

### ISSUE THREAD

**Issue by dave-burke** [skill-collectors/weather-app#189]
Ensure that we are counting each API call separately and show the totals in the "settings" modal where the user inputs their API key.

Alternately, we could just remove the use of count-api, but it's kind of fun.

**Comment by mjp2233** [comment]
Clount API is being removed in the Comprehensive Upgrade PR. This issue is no longer applicable. https://github.com/skill-collectors/weather-app/pull/480
