### ISSUE TITLE
Choose a weather API

### ISSUE THREAD

**Issue by dave-burke** [skill-collectors/weather-app#4]
Most APIs cost money, or have limits to the number of requests. Ideally we'd want one that's totally free. We might also consider supporting multiple APIs and allowing the user to set their own API key so they can pay for their own usage or monitor their own request count.

Here's a list to get us started:

https://github.com/public-apis/public-apis#weather

and there is also https://www.weather.gov/documentation/services-web-api

**Comment by bburggraff** [comment]
Looking through the list, there doesn't seem to be an actual 'free' option, although some seem more generous than others. 

I like the idea of using weather.gov, but it requires lat/long coordinates, so we'd have to leverage a separate geocoding (their FAQ's have a list of free and paid options: https://weather-gov.github.io/api/general-faqs)

I think an ideal end state would be to allow the app to use a user-specified api. As @LFTRPLLR asked, I think our 'secret sauce' could be giving that level of flexibility. 

As for an api to start with, https://openweathermap.org/ seems pretty robust, is well documented, and has a generous free account tier. This might be the easiest option for getting up and running, and having all of the api documentation will make it easier to mock out calls as we do our development/testing.

**Comment by mjp2233** [comment]
I would agree that OpenWeather is our best option. The other APIs I looked at were not as well documented or didn't have as many features.

I also like the idea of letting the user monitor their API calls or set their own API. It would give an opportunity for different people to work on different APIs. Although I do think we should start with just one and build out these advanced features after the OpenWeather API (or whichever one we pick) is working as we want it to.

**Comment by dave-burke** [comment]
We're going to start with OpenWeather. Each dev can create their own account and store the key in a local environment file. In the future, we can create a UI to allow the user to paste in their own key, support other APIs, and provide some sensible defaults.
